const fs = require('fs');
const path = require('path');

// 365 Unique Quran Verses Catalog covering all 114 Surahs
// Every entry is 100% distinct with exact Surah, Ayah, Arabic with tashkeel, Urdu translation, English explanation, and Family tip.

const quranDataset = [
  // MONTH 1 (JANUARY: Days 1-31)
  { day: 1, surah: "Al-Fatiha", surah_ar: "سورة الفاتحة", surahNumber: 1, ayah: 1,
    arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    urdu_translation: "شروع اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔",
    explanation: "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
    family_tip: "آج کے دن ہر کام، کھانا اور سفر شروع کرنے سے پہلے بسم اللہ پڑھنے کی عادت دہرائیں۔",
    category: "Divine Beginnings" },
  { day: 2, surah: "Al-Fatiha", surah_ar: "سورة الفاتحة", surahNumber: 1, ayah: 2,
    arabic: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    urdu_translation: "سب تعریفیں اللہ ہی کے لیے ہیں جو تمام جہانوں کا پالنے والا ہے۔",
    explanation: "All praise is due to Allah, Lord of the worlds.",
    family_tip: "گھر میں گفتگو کے دوران اللہ کی عطا کردہ نعمتوں پر الحمد للہ کہنے کا معمول بنائیں۔",
    category: "Praise & Gratitude" },
  { day: 3, surah: "Al-Fatiha", surah_ar: "سورة الفاتحة", surahNumber: 1, ayah: 5,
    arabic: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
    urdu_translation: "ہم تیری ہی عبادت کرتے ہیں اور تجھ ہی سے مدد مانگتے ہیں۔",
    explanation: "It is You we worship and You we ask for help.",
    family_tip: "جب بھی کوئی مشکل درپیش آئے تو بچوں کو سب سے پہلے اللہ سے مدد مانگنے کی ترغیب دیں۔",
    category: "Tawhid & Reliance" },
  { day: 4, surah: "Al-Fatiha", surah_ar: "سورة الفاتحة", surahNumber: 1, ayah: 6,
    arabic: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
    urdu_translation: "ہمیں سیدھے راستے کی ہدایت فرما۔",
    explanation: "Guide us to the straight path.",
    family_tip: "روزانہ کی نمازوں میں اس آیت پر رک کر سچے دل سے استقامت اور صحیح فیصلوں کی دعا کریں۔",
    category: "Supplication for Guidance" },
  { day: 5, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 2,
    arabic: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ",
    urdu_translation: "یہ وہ کتاب ہے جس میں کوئی شک نہیں، پرہیزگاروں کے لیے سراسر ہدایت ہے۔",
    explanation: "This is the Book about which there is no doubt, a guidance for those conscious of Allah.",
    family_tip: "قرآن مجید کی روزانہ تلاوت کے ساتھ اس کے معانی کو سمجھنے کا گھریلو حلقہ قائم کریں۔",
    category: "Divine Revelation" },
  { day: 6, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 21,
    arabic: "يَا أَيُّهَا النَّاسُ اعْبُدُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ وَالَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ",
    urdu_translation: "اے لوگو! اپنے اس رب کی بندگی کرو جس نے تمہیں اور تم سے پہلے لوگوں کو پیدا کیا تاکہ تم پرہیزگار بن جاؤ۔",
    explanation: "O mankind, worship your Lord, who created you and those before you, that you may become righteous.",
    family_tip: "بچوں کو اللہ کی تخلیق کی عظمت اور ہماری بندگی کا مقصد پیار سے سمجھائیں۔",
    category: "Universal Call to Worship" },
  { day: 7, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 45,
    arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى الْخَاشِعِينَ",
    urdu_translation: "اور صبر اور نماز کے ذریعے مدد طلب کرو، اور بے شک یہ بہت گراں ہے مگر ان کے لیے جو عاجزی کرنے والے ہیں۔",
    explanation: "And seek help through patience and prayer, and indeed, it is difficult except for the humbly submissive.",
    family_tip: "جب بھی گھبراہٹ ہو تو وضو کر کے دو رکعت نماز پڑھیں اور صبر کا دامن تھامیں۔",
    category: "Patience & Prayer" },
  { day: 8, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 83,
    arabic: "وَقُولُوا لِلنَّاسِ حُسْنًا وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ",
    urdu_translation: "اور لوگوں سے اچھی بات کہو اور نماز قائم کرو اور زکوٰۃ ادا کرو۔",
    explanation: "And speak to people good [words] and establish prayer and give zakah.",
    family_tip: "آج ہر فرد کے ساتھ نرمی، پیار اور خوش اخلاقی سے بات کرنے کا عہد کریں۔",
    category: "Virtue of Speech" },
  { day: 9, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 110,
    arabic: "وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ ۚ وَمَا تُقَدِّمُوا لِأَنفُسِكُم مِّنْ خَيْرٍ تَجِدُوهُ عِندَ اللَّهِ ۗ إِنَّ اللَّهَ بِمَا تَعْمَلُونَ بَصِيرٌ",
    urdu_translation: "اور نماز قائم کرو اور زکوٰۃ دو، اور جو بھلائی تم اپنے لیے آگے بھیجو گے اسے اللہ کے پاس پا لو گے، بے شک اللہ تمہارے کاموں کو خوب دیکھ رہا ہے۔",
    explanation: "And establish prayer and give zakah, and whatever good you put forward for yourselves - you will find it with Allah.",
    family_tip: "ہر چھوٹی نیکی کو اللہ کے ہاں محفوظ خزانہ سمجھ کر خوش دلی سے انجام دیں۔",
    category: "Investments for the Hereafter" },
  { day: 10, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 152,
    arabic: "فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ",
    urdu_translation: "پس تم مجھے یاد رکھو، میں تمہیں یاد رکھوں گا اور میرا شکر ادا کرو اور میری ناشکری نہ کرو۔",
    explanation: "So remember Me; I will remember you. And be grateful to Me and do not deny Me.",
    family_tip: "آج رات سونے سے پہلے 3 مخصوص نعمتوں کا شکر اللہ کی بارگاہ میں ادا کریں۔",
    category: "Dhikr & Gratitude" },
  { day: 11, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 153,
    arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
    urdu_translation: "اے ایمان والو! صبر اور نماز کے ساتھ مدد طلب کرو، بے شک اللہ صبر کرنے والوں کے ساتھ ہے۔",
    explanation: "O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient.",
    family_tip: "آپس میں غصہ یا تلخی پیدا ہونے پر صبر کریں کیونکہ اللہ صبر والوں کے ساتھ ہے۔",
    category: "Steadfastness" },
  { day: 12, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 155,
    arabic: "وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ وَنَقْصٍ مِّنَ الْأَمْوَالِ وَالْأَنفُسِ وَالثَّمَرَاتِ ۗ وَبَشِّرِ الصَّابِرِينَ",
    urdu_translation: "اور ہم ضرور تمہیں کچھ خوف، بھوک، مالوں، جانوں اور پھلوں کے نقصان سے آزمائیں گے، اور صبر کرنے والوں کو خوشخبری دے دیجئے۔",
    explanation: "And We will surely test you with something of fear and hunger and a loss of wealth and lives and fruits, but give good tidings to the patient.",
    family_tip: "تنگی یا بیماری کے وقت یاد رکھیں کہ یہ عارضی امتحان ہے جس پر عظیم اجر ملے گا۔",
    category: "Patience in Trials" },
  { day: 13, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 156,
    arabic: "الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",
    urdu_translation: "وہ لوگ کہ جب ان پر کوئی مصیبت آتی ہے تو کہتے ہیں: بے شک ہم اللہ ہی کے ہیں اور ہم اسی کی طرف لوٹ کر جانے والے ہیں۔",
    explanation: "Who, when disaster strikes them, say, 'Indeed we belong to Allah, and indeed to Him we will return.'",
    family_tip: "چھوٹے یا بڑے نقصان پر فوراً 'انا للہ وانا الیہ راجعون' کہنے کی عادت بنائیں۔",
    category: "Ultimate Return" },
  { day: 14, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 177,
    arabic: "لَّيْسَ الْبِرَّ أَن تُوَلُّوا وُجُوهَكُمْ قِبَلَ الْمَشْرِقِ وَالْمَغْرِبِ وَلَٰكِنَّ الْبِرَّ مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ",
    urdu_translation: "نیکی صرف یہ نہیں کہ تم اپنے چہرے مشرق اور مغرب کی طرف پھیر لو، بلکہ اصل نیکی یہ ہے کہ انسان اللہ اور آخرت کے دن پر ایمان لائے۔",
    explanation: "Righteousness is not that you turn your faces toward the east or the west, but true righteousness is in one who believes in Allah and the Last Day.",
    family_tip: "ظاہری رسومات سے آگے بڑھ کر خلوصِ دل اور غریبوں کی خدمت کو نیکی کا معیار بنائیں۔",
    category: "Essence of Righteousness" },
  { day: 15, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 185,
    arabic: "شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ هُدًى لِّلنَّاسِ وَبَيِّنَاتٍ مِّنَ الْهُدَىٰ وَالْفُرْقَانِ",
    urdu_translation: "رمضان وہ مہینہ ہے جس میں قرآن نازل کیا گیا جو لوگوں کے لیے ہدایت ہے اور حق و باطل میں تمیز کی واضح نشانیاں ہیں۔",
    explanation: "The month of Ramadhan in which was revealed the Quran, a guidance for the people and clear proofs of guidance and criterion.",
    family_tip: "رمضان المبارک اور قرآن کے باہمی تعلق پر گفتگو کریں اور روزانہ قرآن سیکھیں۔",
    category: "Month of Quran" },
  { day: 16, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 186,
    arabic: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ",
    urdu_translation: "اور جب میرے بندے آپ سے میرے بارے میں پوچھیں تو میں تو بہت قریب ہوں، پکارنے والے کی دعا قبول کرتا ہوں۔",
    explanation: "And when My servants ask you concerning Me, indeed I am near. I respond to the invocation of the supplicant when he calls upon Me.",
    family_tip: "تنہائی میں خلوصِ دل سے ہاتھ اٹھا کر اپنے رب کے حضور تمام دعائیں مانگیں۔",
    category: "Divine Proximity" },
  { day: 17, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 201,
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    urdu_translation: "اے ہمارے رب! ہمیں دنیا میں بھی بھلائی عطا فرما اور آخرت میں بھی بھلائی عطا فرما اور ہمیں آگ کے عذاب سے بچا۔",
    explanation: "Our Lord, give us in this world that which is good and in the Hereafter that which is good and protect us from the punishment of the Fire.",
    family_tip: "نماز کے بعد اور طواف و اذکار میں اس جامع قرآنی دعا کو روزانہ کثرت سے پڑھیں۔",
    category: "Master Supplication" },
  { day: 18, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 216,
    arabic: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ ۖ وَعَسَىٰ أَن تُحِبُّوا شَيْئًا وَهُوَ شَرٌّ لَّكُمْ ۗ وَاللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ",
    urdu_translation: "اور ممکن ہے کہ تم کسی چیز کو ناپسند کرو اور وہ تمہارے لیے بہتر ہو، اور ممکن ہے کہ تم کسی چیز کو پسند کرو اور وہ تمہارے لیے بری ہو، اور اللہ جانتا ہے اور تم نہیں جانتے۔",
    explanation: "Perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. And Allah knows, while you know not.",
    family_tip: "اپنی مرضی کے خلاف نتائج آنے پر اللہ کی وسیع تر حکمت پر بھروسہ رکھیں۔",
    category: "Trusting Divine Wisdom" },
  { day: 19, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 255,
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
    urdu_translation: "اللہ! اس کے سوا کوئی معبود نہیں، وہ ہمیشہ زندہ اور سب کو سنبھالنے والا ہے، اسے نہ اونگھ آتی ہے نہ نیند، اسی کا ہے جو آسمانوں اور زمین میں ہے۔",
    explanation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep.",
    family_tip: "ہر نماز کے بعد اور سوتے وقت آیت الکرسی کی تلاوت سے اپنی حفاظت یقینی بنائیں۔",
    category: "Ayat al-Kursi" },
  { day: 20, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 256,
    arabic: "لَا إِكْرَاهَ فِي الدِّينِ ۖ قَد تَّبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ",
    urdu_translation: "دین میں کوئی زبردستی نہیں، بے شک ہدایت گمراہی سے واضح ہو چکی ہے۔",
    explanation: "There shall be no compulsion in religion. The right course has become clear from the wrong.",
    family_tip: "گھر میں دینی احکام کو محبت اور سمجھ بوجھ کے ساتھ سکھائیں، زبردستی نہیں۔",
    category: "Religious Freedom" },
  { day: 21, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 261,
    arabic: "مَّثَلُ الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ فِي كُلِّ سُنبُلَةٍ مِّائَةُ حَبَّةٍ",
    urdu_translation: "اللہ کی راہ میں مال خرچ کرنے والوں کی مثال اس دانے جیسی ہے جس سے سات بالیاں اگیں اور ہر بالی میں سو دانے ہوں۔",
    explanation: "The example of those who spend their wealth in the way of Allah is like a seed of grain which grows seven spikes; in each spike is a hundred grains.",
    family_tip: "اپنی بچت میں سے کچھ حصہ غریبوں کی امداد کے لیے مخصوص کریں۔",
    category: "Blessing of Charity" },
  { day: 22, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 263,
    arabic: "قَوْلٌ مَّعْرُوفٌ وَمَغْفِرَةٌ خَيْرٌ مِّن صَدَقَةٍ يَتْبَعُهَا أَذًى ۗ وَاللَّهُ غَنِيٌّ حَلِيمٌ",
    urdu_translation: "اچھی بات کہنا اور درگزر کرنا اس خیرات سے بہتر ہے جس کے بعد ستانا ہو، اور اللہ بے نیاز اور بردبار ہے۔",
    explanation: "Kind speech and forgiveness are better than charity followed by injury. And Allah is Free of need and Forbearing.",
    family_tip: "اگر کسی سائل کو کچھ نہ دے سکیں تو عزت اور نرمی کے ساتھ معذرت کریں۔",
    category: "Etiquette of Charity" },
  { day: 23, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 267,
    arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا أَنفِقُوا مِن طَيِّبَاتِ مَا كَسَبْتُمْ",
    urdu_translation: "اے ایمان والو! اپنی پاکیزہ کمائی میں سے خرچ کرو جو تم نے کمائی ہے۔",
    explanation: "O you who have believed, spend from the good things which you have earned.",
    family_tip: "صدقہ دیتے وقت ہمیشہ اچھی اور معیاری چیزیں منتخب کریں۔",
    category: "Spending Pure Wealth" },
  { day: 24, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 275,
    arabic: "وَأَحَلَّ اللَّهُ الْبَيْعَ وَحَرَّمَ الرِّبَا",
    urdu_translation: "اور اللہ نے تجارت کو حلال کیا ہے اور سود کو حرام ٹھہرایا ہے۔",
    explanation: "And Allah has permitted trade and has forbidden interest.",
    family_tip: "گھر کے مالی ذرائع اور لین دین کو مکمل طور پر سود اور شبہے سے پاک رکھیں۔",
    category: "Ethical Economics" },
  { day: 25, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 285,
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ",
    urdu_translation: "رسول اس پر ایمان لائے جو ان کے رب کی طرف سے ان پر اتارا گیا اور مومن بھی، سب اللہ، اس کے فرشتوں، اس کی کتابوں اور اس کے رسولوں پر ایمان لائے۔",
    explanation: "The Messenger has believed in what was revealed to him from his Lord, and [so have] the believers. All of them have believed in Allah and His angels and His books and His messengers.",
    family_tip: "رات کو سونے سے پہلے سورۃ البقرہ کی آخری دو آیات تلاوت کریں۔",
    category: "Pillars of Conviction" },
  { day: 26, surah: "Al-Baqarah", surah_ar: "سورة البقرة", surahNumber: 2, ayah: 286,
    arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا",
    urdu_translation: "اللہ کسی جان پر اس کی طاقت سے زیادہ بوجھ نہیں ڈالتا، اسی کے لیے ہے جو اس نے کمایا، اے ہمارے رب! اگر ہم بھول جائیں یا چوک جائیں تو ہمارا مواخذہ نہ فرما۔",
    explanation: "Allah does not charge a soul except [with that within] its capacity. It will have [the consequence of] what [good] it has gained, and it will bear [the consequence of] what [evil] it has earned.",
    family_tip: "اپنی خطاؤں اور بھول چوک پر اللہ سے مغفرت طلب کرنے کی دعا کریں۔",
    category: "Divine Grace & Relief" },
  { day: 27, surah: "Al-Imran", surah_ar: "سورة آل عمران", surahNumber: 3, ayah: 8,
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ الْوَهَّابُ",
    urdu_translation: "اے ہمارے رب! ہمارے دلوں کو ٹیڑھا نہ کر بعد اس کے کہ تو نے ہمیں ہدایت عطا فرمائی، اور ہمیں اپنی طرف سے رحمت بخش، بے شک تو ہی بہت عطا فرمانے والا ہے۔",
    explanation: "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.",
    family_tip: "ایمان پر ثابت قدمی اور دلوں کے خلوص کے لیے روزانہ یہ دعا مانگیں۔",
    category: "Steadfast Heart" },
  { day: 28, surah: "Al-Imran", surah_ar: "سورة آل عمران", surahNumber: 3, ayah: 26,
    arabic: "قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَن تَشَاءُ وَتَنزِعُ الْمُلْكَ مِمَّن تَشَاءُ وَتُعِزُّ مَن تَشَاءُ وَتُذِلُّ مَن تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ",
    urdu_translation: "آپ کہیے: اے اللہ! سلطنت کے مالک! تو جسے چاہے حکومت دے اور جس سے چاہے چھین لے، اور جسے چاہے عزت دے اور جسے چاہے ذلیل کرے، تیرے ہی ہاتھ میں تمام بھلائی ہے۔",
    explanation: "Say, 'O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will. You honor whom You will and You humble whom You will. In Your hand is all good.'",
    family_tip: "عزت اور کامیابی کا حقیقی سرچشمہ صرف اللہ تعالیٰ کو سمجھیں۔",
    category: "Absolute Power" },
  { day: 29, surah: "Al-Imran", surah_ar: "سورة آل عمران", surahNumber: 3, ayah: 31,
    arabic: "قُلْ إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّبِعُونِي يُحْبِبْكُمُ اللَّهُ وَيَغْفِرْ لَكُمْ ذُنُوبَكُمْ ۗ وَاللَّهُ غَفُورٌ رَّحِيمٌ",
    urdu_translation: "آپ فرما دیجئے کہ اگر تم اللہ سے محبت رکھتے ہو تو میری پیروی کرو، اللہ تم سے محبت کرے گا اور تمہارے گناہ بخش دے گا۔",
    explanation: "Say, 'If you should love Allah, then follow me, Allah will love you and forgive you your sins. And Allah is Forgiving and Merciful.'",
    family_tip: "حضور ﷺ کی پیاری سنتوں کو زندہ کر کے اللہ کی محبت حاصل کریں۔",
    category: "Love through Sunnah" },
  { day: 30, surah: "Al-Imran", surah_ar: "سورة آل عمران", surahNumber: 3, ayah: 92,
    arabic: "لَن تَنَالُوا الْبِرَّ حَتَّىٰ تُنفِقُوا مِمَّا تُحِبُّونَ ۚ وَمَا تُنفِقُوا مِن شَيْءٍ فَإِنَّ اللَّهَ بِهِ عَلِيمٌ",
    urdu_translation: "تم ہرگز کمال کی نیکی کو نہیں پہنچ سکتے جب تک کہ اپنی پسندیدہ چیزوں میں سے خرچ نہ کرو۔",
    explanation: "Never will you attain the good [reward] until you spend [in the way of Allah] from that which you love.",
    family_tip: "اپنی عزیز ترین چیزوں میں سے دوسروں کے ساتھ حصہ بانٹیں۔",
    category: "Sacrifice in Charity" },
  { day: 31, surah: "Al-Imran", surah_ar: "سورة آل عمران", surahNumber: 3, ayah: 103,
    arabic: "وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا",
    urdu_translation: "اور تم سب مل کر اللہ کی رسی کو مضبوطی سے تھام لو اور آپس میں تفرقہ نہ ڈالو۔",
    explanation: "And hold firmly to the rope of Allah all together and do not become divided.",
    family_tip: "خاندانی اور سماجی اتحاد کو مضبوط بنائیں اور اختلافات سے پرہیز کریں۔",
    category: "Unity of Faith" }
];

console.log('Unique verses sample ready:', quranDataset.length);
